pre_training:
  n_epochs: 100
  checkpoint: "runs/pretrain-checkpoints"
  log: "runs/pretrain-logs"
  milestones: [40, 80]
  lr: 0.1

fewshot_training:
  ways: 5
  shots: 5
  queries: 15
  checkpoint: "runs/fewshot-checkpoints"
  log: "runs/fewshot-logs"
